[font]
normal = { family = "Inconsolata Nerd Font Mono", style = "Regular" }
size = 15

[window]
dimensions = { columns = 95, lines = 27 }

[colors]
# Default colors
[colors.primary]
background = '#272822'
foreground = '#fdfff1'

# Normal colors
[colors.normal]
black   = '#161613'
red     = '#f92672'
green   = '#a6e22e'
yellow  = '#e6db74'
blue    = '#66d9ef'
magenta = '#ae81ff'
cyan    = '#66d9ef'
white   = '#fdfff1'

# Normal colors
[colors.bright]
black   = '#161613'
red     = '#f92672'
green   = '#a6e22e'
yellow  = '#e6db74'
blue    = '#66d9ef'
magenta = '#ae81ff'
cyan    = '#66d9ef'
white   = '#fdfff1'

